host = "localhost"
port = 3306
user = "root"
<<<<<<< HEAD
<<<<<<< HEAD
password = "amilaMa@123MYSQL"
=======
password = "pllk"
>>>>>>> 7f0b579a9f498bbbb5cf3e7cd2e439a31e6f7d09
=======
password = "amilaMa@123MYSQL"
>>>>>>> c8a088cf3499610ac04a08c1d0c76e4f862303f8
database = "doctor_appointment_system"